language: python
jobs:
  include:
    - python: "2.7"
    - python: "3.4"
    - python: "3.5"
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "pypy"
install:
  - pip install -r requirements.txt
  - python -c 'import sys; sys.exit(sys.version_info[:2] >= (3, 5))' || pip install -r requirements-async.txt
script: py.test --cov --cov-report term-missing --cov-fail-under=100
services:
  - redis-server
